- id: doi:10.1111/ele.14215
  date: 2023-4-20
  members:
    - Xiangtao Xu
    - Yixin Ma
  tags:
    - Functional Ecology
    - Remote sensing
    - TLS

- id: doi:10.5194/bg-20-2117-2023
  date: 2023-06-14
  members:
    - Xiangtao Xu
  tags:
    - Drought
    - Forest moratlity
    - ED2

- id: doi:10.1126/sciadv.add5667
  date: 2023-1-18
  members:
    - Xiangtao Xu
  tags:
    - Functional Ecology
    - Eco-Evo Optimality

- id: doi:10.1111/gcb.16046
  date: 2022-3-1
  members:
    - Xiangtao Xu
    - Donghai Wu
  tags:
    - Remote sensing
    - Ecosystem resilience
    - Forest mortality

- id: doi:10.1371/journal.pbio.3001322
  date: 2021-8-19
  members:
    - Daniel F. Petticord
  tags:
    - Marine ecology

- id: doi:10.1111/gcb.15872
  date: 2021-9-3
  members:
    - Xiangtao Xu
  tags:
    - Tree mortality
    - Remote sensing

- id: doi:10.1111/ele.13879
  date: 2021-9-12
  members:
    - Xiangtao Xu
    - Donghai Wu
  tags:
    - Radiocarbon
    - Tibetan Plateau
    - Soil carbon turnover

- id: doi:10.1029/2020JG005976
  date: 2021-4-1
  members:
    - Xiangtao Xu
  tags:
    - Remote sensing
    - Tree mortality

- id: doi:10.1111/nph.17254
  date: 2021-6-1
  members:
    - Xiangtao Xu
    - Donghai Wu
  tags:
    - Remote sensing
    - Tropical ecology
    - ED2

- id: doi:d10.1111/1365-2745.13540
  date: 2021-3-3
  members:
    - Xiangtao Xu
  tags:
    - ED2
    - Tropical ecology

- id: doi:10.1016/j.isprsjprs.2020.10.017
  date: 2021-1-15
  members:
    - Xiangtao Xu
  tags:
    - Phenology
    - Remote sensing

- id: doi:10.1007/s40641-020-00168-6
  date: 2021-1-12
  members:
    - Xiangtao Xu
  tags:
    - Review

- id: doi:10.1111/gcb.15224
  date: 2020-8-30
  members:
    - Xiangtao Xu
    - Donghai Wu
  tags:
    - Carbon turnover

- id: doi:10.1111/nph.16712
  date: 2020-6-22
  members:
    - Xiangtao Xu
  tags:
    - Phenology
    - Optimality principles

- id: doi:10.1111/gcb.15037
  date: 2020-3-23
  members:
    - Xiangtao Xu
  tags:
    - Tropical ecology
    - Tree mortality

- id: doi:10.1111/nph.16275
  date: 2020-1-24
  members:
    - Xiangtao Xu
  tags:
    - Tropical ecology
    - Allometry
    - Root
    - ED2

- id: doi:10.1038/s41467-019-13656-7
  date: 2019-12-2
  members:
    - Xiangtao Xu
  tags:
    - Tropical ecology
    - Nitrogen fixation
    - ED2
