---
title: "New paper published in Global Change Biology"
date: "2024-08-09"
description: "New paper on two sub-annual timescales of terrestrial water and carbon cycling is published in Global Change Biology."
categories: [Publication, Ecohydrology]
---

New paper titled "Two sub-annual timescales and coupling modes for terrestrial water and carbon cycles" is now published [online](https://onlinelibrary.wiley.com/doi/10.1111/gcb.17463) in *Global Change Biology*. Dr. Dan Gianotti from MIT CEE is the lead author while Xiangtao Xu of the BioM2 Lab is a co-author. Using remote sensing data, the study identifies two dominant modes of terrestrial water and carbon cycles across the contiguous United States: (1) a negative-correlation timescale on the order of a few days, during which landscapes dry after precipitation and plants increase their carbon uptake through photosynthetic upregulation, and (2) a slow, seasonal-scale positive covariation through which landscape drying leads to decreased growth and carbon uptake. The spatial pattern of local temporal dynamics — positively sloped tangent lines to a convex long-term mean-state curve — is surprisingly strong and can serve as a benchmark for coupled Earth System Models. The study shows that many such models do not represent this emergent mean-state pattern, and hypothesizes that this may be due to a lack of water-carbon feedbacks at daily scales.
